name: Maven Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test on Java 17"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v2

      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
          cache: "maven"

      - name: "Install Maven 3.9.9"
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
          tar -xvf apache-maven-3.9.9-bin.tar.gz
          echo "export PATH=\$(pwd)/apache-maven-3.9.9/bin:\$PATH" >> $GITHUB_ENV

      - name: "Run Maven Test"
        run: mvn test
